# Stage Environmen
accessKey:74558f2f-8c68-471f-9af2-4c03fbe6b119
username:autotest01
deviceName:Android GoogleAPI Emulator
deviceOrientation:portrait
platformName:Android
platformVersion:9.0
browserName:
appPackage:com.legrand.homecontrol
appActivity:com.netetmo.legrand.dashboard.DashboardActivity
app:sauce-storage:app-api-beta.apk
endpointUrl=https://www.sta.acweb.bticino.com
implicitlyWait=30
explicityWait=30
pageLoadWait=5
imageLoadWait=3
highlightTime=6000
popupLoadWait=3
emailFrom=admin-acweb.stg@legrand.fr
userProfile1=env/user_04.properties
userProfile2=env/user_05.properties
userProfile3=env/user_06.properties
userProfile4=env/user_11.properties
userProfile5=env/user_15.properties
PlantName=NTT_PLANT
PlantConfig=env/Plant_NTT_Config_file.xml
BadgeID=B1852C72
notepadApp=C:/Windows/System32/notepad.exe
excelApp=C:/Program Files (x86)/Microsoft Office/Office16/EXCEL.EXE